version: '3.1'

networks:
  network:
    driver: bridge

services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: always
    environment:
      - MONGODB_USER:admin
      - MONGODB_PASS:all0.1EN2.3ce
      - MONGODB_DATABASE=admin
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: all0.1EN2.3ce
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: all0.1EN2.3ce
    links:
      - mongo:mongo
    networks:
      - network
    depends_on:
      - mongo
volumes:
  mongo_data: {}